#!/bin/bash

jobfile=fio_vm_${ioengine}_${blocksize}
[ "${jobfile#*__}" != "$jobfile" ] && {
    echo "error composing $jobfile: missing options" >&2
    exit 1
}

cat > $jobfile <<EOF
[global]
direct=1
blocksize=$blocksize
filename=$filename
numjobs=1
group_reporting
size=$size

[seq-write]
rw=randwrite
ioengine=libaio
blocksize=64k
iodepth=64
stonewall

[seq-read]
rw=randread
ioengine=libaio
blocksize=64k
iodepth=64
stonewall

[rand-write]
rw=randwrite
ioengine=libaio
blocksize=4k
iodepth=128
stonewall

[rand-read]
rw=randread
ioengine=libaio
blocksize=4k
iodepth=128
stonewall

EOF
