#!/bin/sh

: ${runtime:=20}

jobfile=fio_lat
[ "${jobfile#*__}" != "$jobfile" ] && {
    echo "error composing $jobfile: missing options" >&2
    exit 1
}

cat > $jobfile <<EOF
[global]
direct=1
filename=$filename
numjobs=1
group_reporting

[seq-write-lat]
rw=write
ioengine=psync
blocksize=512
runtime=$runtime
stonewall

[seq-read-lat]
rw=read
ioengine=psync
blocksize=512
runtime=$runtime
stonewall
EOF
