#!/bin/sh

: ${runtime:=20}

jobfile=fio_ebs
[ "${jobfile#*__}" != "$jobfile" ] && {
    echo "error composing $jobfile: missing options" >&2
    exit 1
}

cat > $jobfile <<EOF
[global]
direct=1
filename=$filename
numjobs=1
group_reporting
size=100%
runtime=$runtime

[seq-write]
ioengine=psync
blocksize=1M
rw=write
stonewall

[seq-read]
ioengine=psync
blocksize=1M
rw=read
stonewall

[rand-write]
rw=randwrite
ioengine=libaio
blocksize=4k
iodepth=32
stonewall

[rand-read]
rw=randread
ioengine=libaio
blocksize=4k
iodepth=32
stonewall

[seq-write-lat]
rw=write
ioengine=psync
blocksize=512
stonewall

[seq-read-lat]
rw=read
ioengine=psync
blocksize=512
stonewall
EOF
