#!/bin/bash

[[ $SRC ]] || export SRC="$(dirname $(dirname $(readlink -e -v $0)))"

usage()
{
    echo "Usage: $0 [-d days_ago] result_path"
    exit 1
}

# default cleanup 14 days ago results
mtime=14

while getopts "d:" opt
do
    case $opt in
    d ) mtime=$OPTARG ;;
    ? ) usage ;;
    esac
done

shift $(($OPTIND-1))

if [ $# -le 0 ]; then
    usage
fi

result_path=$1

date +'%F %T Start up'
find $result_path -type d -mtime +$mtime -regex '.*/....-..-..-..:..:..$' -print0 | xargs -0 -n10 -i sh -c 'echo Cleanup {}; rm -rf {}'
