#!/usr/bin/env python

import os
import sys
import argparse

SRC = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir))
LIB_PATH = SRC + '/lib'
sys.path.insert(0, LIB_PATH)

import job
import common

parser = argparse.ArgumentParser()
parser.add_argument('-o', '--output', help="output path", type=str)
parser.add_argument('-t', '--testbox', help="--test-box HOSTNAME", type=str)
parser.add_argument('--no-defaults', help="do not load the defaults headers", type=str, default="no")
parser.add_argument('-j', '--jobs', help="specify job files", nargs='+', type=str)

if len(sys.argv) == 1:
    parser.print_help()
    sys.exit(1)

args = parser.parse_args()

output_path = args.output
if not output_path:
    sys.stderr.write(r"Use '-o' to specify output path" + '\n')
    sys.exit(1)
elif not os.path.isdir(output_path):
    sys.stderr.write("%s: no such direcotory\n" % output_path)
    sys.exit(1)

if not args.testbox:
    opt_testbox = os.getenv("HOSTNAME")
atom_jobs = []

def test_func(job):
    job_params = job.path_params()
    unit_jobfile = prefix + '-' + job_params
    # there is a ['xxx', 'yyy'] bug in unit_jobfile, still not find it
    # maybe first jump it
    if '[' in unit_jobfile:
        return
    if 'commit' in job:
        unit_jobfile += '-' + job['commit']
    job['job_params'] = job_params
    job['unit_job'] = unit_jobfile.split('/')[-1]
    unit_jobfile += '.yaml'
    job.save(unit_jobfile)
    print "%s => %s" % (jobfile, unit_jobfile)

for jobfile in args.jobs:
    jobs = job.Job()

    if args.no_defaults == "no":
        #jobs.load_head("%s/jobs/DEFAULTS" % SRC)
        jobs.load_head("%s/hosts/%s" % (SRC, opt_testbox), True)

    jobs.load(jobfile)

    jobs.job['enque_time'] = common.get_time()
    prefix = args.output + os.sep + os.path.splitext(os.path.basename(jobfile))[0]

    jobs.each_jobs(test_func)

