#!/bin/sh
### BEGIN INIT INFO
# Provides:          pst-server
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: perf-scripts/server/server.py
# Description:       perf-scripts/server/server.py
### END INIT INFO

# Call this script at boot time.

export SRC=/opt/perf-scripts
$SRC/server/server.py
