#!/bin/bash

download()
{
    [ -d '/tmp/ebizzy-0.3' ] && rm -rf /tmp/ebizzy-0.3
    git_clone_update https://git.oschina.net/ZexiLi/ebizzy-0.3.git
    source_dir="/tmp/ebizzy-0.3"
}

install()
{
	cp -af $BM_NAME $BM_ROOT
}
