#!/usr/bin/env python

import sys
import re

for line in sys.stdin:
    m1 = re.search(r'server-create.*cost: ([\d]+) seconds', line)
    m2 = re.search(r'server-list.*cost: ([\d]+) seconds', line)
    m3 = re.search(r'server-delete.*cost: ([\d]+) seconds', line)
    if m1:
        print("create_sec: " + m1.group(1))
    elif m2:
        print("list_sec: " + m2.group(1))
    elif m3:
        print("delete_sec: " + m3.group(1))
