#!/usr/bin/env python

import sys
import re

for line in sys.stdin:
    query_time = re.search(r'^;;.*Query time: ([\d]+) msec', line)
    if query_time:
        print "query_time: " + str(query_time.group(1))
