#!/usr/bin/env python2.7

import sys
import re
import numpy

for line in sys.stdin:
    m1 = re.search(r'^(\d+) records/s(.*)$', line)
    m2 = re.search(r'^real +(\d+.\d+) s', line)
    m3 = re.search(r'^user +(\d+.\d+) s', line)
    m4 = re.search(r'^sys +(\d+.\d+) s', line)
    if m1:
        print 'throughput: ' + m1.group(1)
        throuput = int(m1.group(1))
        data = map(int, m1.group(2).split())
        print 'throuput.per_thread.min: ' + str(min(data))
        print 'throuput.per_thread.max: ' + str(max(data))
        print 'throuput.per_thread.stddev_percent: ' + str(100.0 * numpy.array(data).std() / throuput)
    elif m2:
        print 'time.real: ' + m2.group(1)
    elif m3:
        print 'time.user: ' + m3.group(1)
    elif m4:
        print 'time.sys: ' + m4.group(1)
