#!/usr/bin/env python

import sys
import re
import subprocess
from distutils.version import StrictVersion
# use fio --output-format=json, just parse the json stream
import json

result = json.load(sys.stdin)

fio_jobs = result.get("jobs")

# judge fio version, version under 2.2.8 not include time
version = subprocess.check_output('fio -v', shell=True).split('-')[1].strip()
if StrictVersion(version) >= StrictVersion('2.2.8'):
    fio_time = result.get("time")
    print 'time: ' + fio_time

for job in fio_jobs:
    if job['jobname'] == 'seq-read':
        res_val = job['read']
        print 'seq_read.throughput: ' + str(float(res_val['bw']))
        print 'seq_read.iops: ' + str(float(res_val['iops']))
        print 'seq_read.lat: ' + str(float(res_val['lat']['mean']))
    if job['jobname'] == 'rand-read':
        res_val = job['read']
        print 'rand_read.throughput: ' + str(float(res_val['bw']))
        print 'rand_read.iops: ' + str(float(res_val['iops']))
        print 'rand_read.lat: ' + str(float(res_val['lat']['mean']))
    if job['jobname'] == 'seq-write':
        res_val = job['write']
        print 'seq_write.throughput: ' + str(float(res_val['bw']))
        print 'seq_write.iops: ' + str(float(res_val['iops']))
        print 'seq_write.lat: ' + str(float(res_val['lat']['mean']))
    if job['jobname'] == 'rand-write':
        res_val = job['write']
        print 'rand_write.throughput: ' + str(float(res_val['bw']))
        print 'rand_write.iops: ' + str(float(res_val['iops']))
        print 'rand_write.lat: ' + str(float(res_val['lat']['mean']))
