#!/usr/bin/env python

import sys
import os
import re

for line in sys.stdin:
    res_m = re.search(r'.*Ops:\s([\d]+)\sTPS:\s([\d]+).*', line)
    if res_m:
        ops = res_m.group(1)
        tps = res_m.group(2)
        print("Ops: %s" % ops)
        print("Tps: %s" % tps)
