#!/usr/bin/env python

import sys
import os
import re

for line in sys.stdin:
    if 'Command being timed: ' in line:
        continue
    key, val = line.split(': ')
    key = re.sub(r'\s+', '_', re.sub(' \([^)]+\)', '', re.sub(r'^\s+', '', key))).lower()
    if key == 'elapsed_time':
        times = val.split(':')
        val = float(times[0]) * 60 + float(times[1])
    print "%s: %s" % (key, val)
