#!/usr/bin/env python

import sys
import re
import os

score = None

for line in sys.stdin:
    m = re.search(r'^System Benchmarks Index Score .* ([0-9\.]+)$', line)
    if m:
        score = m.group(1)

if score:
    print 'score: ' + score
else:
    print 'incomplete_result: 1'
    sys.stderr.write("unixbench: missing score, check " + os.getenv('RESULT_ROOT'))
